### ISSUE TITLE
Linux - model_pipeline fails in generate_model, due to failing to find DB table

### ISSUE THREAD

**Issue by calebglawson** [calebglawson/twint-sklearn-twitter-classifier#4]
DB is present, table is present and populated with data.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/sql.py", line 1586, in execute
    cur.execute(*args, **kwargs)
sqlite3.OperationalError: no such table: user_stats

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "model_pipeline.py", line 61, in <module>
    generate_model.run(ARGS)
  File "/github.com/twint-sklearn-twitter-classifier/generate_model.py", line 165, in run
    dataframe, df_bkp = fetch_data(args.database)
  File "/github.com/twint-sklearn-twitter-classifier/generate_model.py", line 18, in fetch_data
    dataframe = pd.read_sql_query("select * from user_stats;", conn)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/sql.py", line 332, in read_sql_query
    chunksize=chunksize,
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/sql.py", line 1633, in read_query
    cursor = self.execute(*args)
  File "/usr/local/lib/python3.7/dist-packages/pandas/io/sql.py", line 1598, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'select * from user_stats;': no such table: user_stats
```

**Comment by calebglawson** [comment]
Paths are different in Windows vs Linux... ( / vs \ ) Wonder if there's a better way to do this that building a string for this argument.

**Comment by calebglawson** [comment]
Pathlib! https://medium.com/@ageitgey/python-3-quick-tip-the-easy-way-to-deal-with-file-paths-on-windows-mac-and-linux-11a072b58d5f

**Comment by calebglawson** [comment]
Bug squashed!
